version: '3.4'

services:
  corepgidentitytest:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      DbPassword: password123
      AppSettings__TestSecret1: HelloWorld
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
        - 5432:5432
    restart: always
    volumes:
        - db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: userone
        POSTGRES_PASSWORD: password123
        POSTGRES_DB: pgtest2

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
volumes:
  db_volume: